export { default as HeroSection } from './HeroSection'
export { default as TimelineSection } from './TimelineSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as SkillsSection } from './SkillsSection'
export { default as ContactSection } from './ContactSection'
